Redefine MSS to mean number of actual data bytes that can fit in a packet, not including SUMIHDRSZ. Previously, MSS included SUMIHDRSZ. This change simplifies some code; no more need for payloadsz or full_payload--it all means MSS now. Where the old MSS definition is needed, use MSS + SUMIHDRSZ.
Configure MTU instead of MSS in client. Add mss2mtu, mtu2mss in
libsumi, allowing for more clarity than mysteriously adding 28.
Should work with other data channels than IP+UDP as well, if added.

sumigetw crashed after writing 30,000 characters to the log:

wx._core.PyAssertionError: C++ assertion "m_count == -1" failed in
..\..\src\msw\textctrl.cpp(122): wrong initial m_updatesCount value


Fix this by clearing the text when its full, and saving client/server
logs to sumigetw-[cs].log.